export function downloadReportPDF({
  title = 'SafaiShield Safety & Rights Report',
  reportText = '',
  evidenceHash = '',
  date = new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' }),
  workerName = 'Sanitation Worker',
  employerName = '',
  locationText = '',
}) {
  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <title>${title}</title>
      <style>
        @page { size: A4; margin: 20mm; }
        body {
          font-family: 'Helvetica Neue', Arial, sans-serif;
          color: #0f172a;
          background: #ffffff;
          line-height: 1.6;
          margin: 0;
          padding: 20px;
        }
        .header {
          border-bottom: 3px solid #dc2626;
          padding-bottom: 15px;
          margin-bottom: 20px;
          display: flex;
          justify-content: space-between;
          align-items: center;
        }
        .header h1 {
          color: #0f172a;
          font-size: 24px;
          margin: 0;
          text-transform: uppercase;
          letter-spacing: 1px;
        }
        .badge {
          background: #fee2e2;
          color: #dc2626;
          font-weight: bold;
          font-size: 11px;
          padding: 6px 12px;
          border-radius: 6px;
          border: 1px solid #fca5a5;
        }
        .meta-grid {
          display: grid;
          grid-template-columns: 1fr 1fr;
          gap: 12px;
          background: #f8fafc;
          border: 1px solid #e2e8f0;
          padding: 15px;
          border-radius: 8px;
          margin-bottom: 20px;
          font-size: 13px;
        }
        .meta-item span {
          color: #64748b;
          font-size: 11px;
          display: block;
          text-transform: uppercase;
          font-weight: bold;
        }
        .report-body {
          background: #ffffff;
          border: 1px solid #cbd5e1;
          padding: 20px;
          border-radius: 8px;
          font-family: 'Courier New', Courier, monospace;
          font-size: 13px;
          white-space: pre-wrap;
          margin-bottom: 20px;
          line-height: 1.7;
        }
        .evidence-box {
          background: #f0fdf4;
          border: 1px solid #bbf7d0;
          border-left: 4px solid #16a34a;
          padding: 12px 15px;
          border-radius: 6px;
          margin-bottom: 20px;
        }
        .evidence-box h4 {
          margin: 0 0 5px 0;
          color: #16a34a;
          font-size: 12px;
          text-transform: uppercase;
        }
        .evidence-hash {
          font-family: monospace;
          font-size: 11px;
          color: #334155;
          word-break: break-all;
        }
        .footer {
          border-top: 1px solid #e2e8f0;
          padding-top: 15px;
          font-size: 11px;
          color: #64748b;
          text-align: center;
        }
      </style>
    </head>
    <body>
      <div class="header">
        <div>
          <h1>🛡️ SafaiShield</h1>
          <p style="margin: 4px 0 0 0; font-size: 12px; color: #64748b;">Confined Space Entry & Worker Rights Evidence Report</p>
        </div>
        <div class="badge">OFFICIAL EVIDENCE RECORD</div>
      </div>

      <div class="meta-grid">
        <div class="meta-item"><span>Report Date</span>${date}</div>
        <div class="meta-item"><span>Worker Name</span>${workerName || 'Anonymous Worker'}</div>
        ${employerName ? `<div class="meta-item"><span>Employer / Contractor</span>${employerName}</div>` : ''}
        ${locationText ? `<div class="meta-item"><span>Location / Coordinates</span>${locationText}</div>` : ''}
      </div>

      <div class="report-body">${reportText}</div>

      ${evidenceHash ? `
        <div class="evidence-box">
          <h4>🔒 SHA-256 Evidence Locker Signature</h4>
          <div class="evidence-hash">${evidenceHash}</div>
          <p style="margin: 5px 0 0 0; font-size: 10px; color: #475569;">
            This cryptographic hash certifies that the recorded safety conditions, time, and violation claims have not been tampered with.
          </p>
        </div>
      ` : ''}

      <div class="footer">
        <p>This report is generated by SafaiShield AI Protection System.</p>
        <p>NAMASTE Helpline: 14473 | National Commission for Safai Karamcharis</p>
      </div>

      <script>
        window.onload = function() {
          window.print();
        };
      </script>
    </body>
    </html>
  `

  const printWindow = window.open('', '_blank')
  if (printWindow) {
    printWindow.document.write(htmlContent)
    printWindow.document.close()
  } else {
    const blob = new Blob([htmlContent], { type: 'text/html' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `SafaiShield_Report_${Date.now()}.html`
    a.click()
    URL.revokeObjectURL(url)
  }
}
